[context."master"]
  command = "cross-env INVESTIGATION='all' yarn deploy"

[context."exploding-stars-staging"]
  command = "cross-env INVESTIGATION='exploding-stars' GATSBY_PLAUSIBLE_DOMAIN='explodingstars.netlify.app' yarn deploy"

[context."expanding-universe-staging"]
  command = "cross-env INVESTIGATION='expanding-universe' GATSBY_PLAUSIBLE_DOMAIN='expandinguniverse.netlify.app' yarn deploy"

[context."observable-universe-staging"]
  command = "cross-env INVESTIGATION='observable-universe' GATSBY_PLAUSIBLE_DOMAIN='observableuniverse.netlify.app' yarn deploy"

[context."solar-system-staging"]
  command = "cross-env INVESTIGATION='solar-system' GATSBY_PLAUSIBLE_DOMAIN='surveyingthesolarsystem.netlify.app' yarn deploy"

[context."hazardous-asteroids-staging"]
  command = "cross-env INVESTIGATION='hazardous-asteroids' GATSBY_PLAUSIBLE_DOMAIN='hazardousasteroids.netlify.app' yarn deploy"

[context."coloring-universe-staging"]
  command = "cross-env INVESTIGATION='coloring-universe' GATSBY_PLAUSIBLE_DOMAIN='coloringtheuniverse.netlify.app' yarn deploy"

[context."window-stars-staging"]
  command = "cross-env INVESTIGATION='window-stars' yarn deploy"

[context."milky-way-staging"]
  command = "cross-env INVESTIGATION='milky-way' yarn deploy"

[context."pcw2020"]
  command = "cross-env INVESTIGATION='pcw-2020' yarn deploy"

[context."demo-mini"]
  command = "cross-env INVESTIGATION='demo-mini' yarn deploy"

[context."ngss-solar-system"]
  command = "cross-env INVESTIGATION='ngss-solar-system' yarn deploy"
