[context."master"]
  command = "cross-env INVESTIGATION='all' yarn deploy"

[context."exploding-stars-staging"]
  command = "cross-env INVESTIGATION='exploding-stars' yarn deploy"

[context."expanding-universe-staging"]
  command = "cross-env INVESTIGATION='expanding-universe' yarn deploy"

[context."observable-universe-staging"]
  command = "cross-env INVESTIGATION='observable-universe' yarn deploy"

[context."solar-system-staging"]
  command = "cross-env INVESTIGATION='solar-system' yarn deploy"

[context."hazardous-asteroids-staging"]
  command = "cross-env INVESTIGATION='hazardous-asteroids' yarn deploy"

[context."coloring-universe-staging"]
  command = "cross-env INVESTIGATION='coloring-universe' yarn deploy"

[context."window-stars-staging"]
  command = "cross-env INVESTIGATION='window-stars' yarn deploy"

[context."milky-way-staging"]
  command = "cross-env INVESTIGATION='milky-way' yarn deploy"
